baseURL = "https://agitated-mccarthy-d537c7.netlify.app/"
languageCode = "en-us"
title = "Site title"
theme = "charaka-hugo-theme-master"

[params]

[params.highlight]
  style = "zenburn"



[[params.social]]
  url = "https://github.com/don1997"
  fa_icon = "fab fa-github"



